spring:
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    vault:
      generic:
        enabled: true
        profile-separator: '/'
        default-context: hackathon-write-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  application:
    name: hackathon-write-service
server:
  port: 0
